# basic
title: Static Map
subtitle: Writing and Ranting
favicon: /images/favicon.ico

# nav #
nav:
  home: .
  archive: archives
  about: /about.html
  rss: /atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

feed:
  type: atom
  path: /atom.xml
  limit: 
  hub:
  content:
