# basic
title: PLACEHOLDER_TITLE
subtitle: PLACEHOLDER_SUBTITLE
favicon: favicon.ico

# Supply your own static images
avatar: images/avatar.png
banner_small: images/banner-small.png
banner_large: images/banner-large.png

# disqus
# disqus_shortname:

# social
social:
 github: https://github.com/
 twitter: https://twitter.com/

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
