# basic
title: Static Map
subtitle: Writing and Ranting
favicon: favicon.ico

# social
social:
 github: https://github.com/kmuncie
 twitter: https://twitter.com/kmuncie

# nav #
nav:
  home: .
  archive: archives
  about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
